# Generated by Django 2.2.6 on 2019-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
