# Generated by Django 2.2.6 on 2019-10-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20191011_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='file',
        ),
    ]
