# Generated by Django 2.2.6 on 2019-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tool_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
